version: "3.7"

services:
  mattermost.app:
    image: mattermost/mattermost-enterprise-edition
    build: ./mattermost
    container_name: mattermost.app
    hostname: mattermost.app
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:password@mattermost.db:5432/mattermost?sslmode=disable&connect_timeout=10
    ports:
      - 8065:8065
    depends_on:
      - mattermost.db
    restart: on-failure

  mattermost.db:
    image: postgres:12.2-alpine
    container_name: mattermost.db
    hostname: mattermost.db
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: mattermost
      POSTGRES_PASSWORD: password
    volumes:
      - ./mattermost/db:/var/lib/postgresql/data
    restart: on-failure

# networks:
#   default:
#     name: mattermost
#     driver: bridge